
# Site settings
title: Guangming Yang
name: Guangming Yang
subtitle: Financial Economist
email: gyang79@wisc.edu
description: >
  PhD student
baseurl: "https://Gyang79.github.io"
url: "https://Gyang79.github.io/"
github_username:  pesoto
disqus_baseurl: "https://Gyang79.github.io/"
disqus_shortname: https-Gyang79-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Guangming"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/Gyang79
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Guangminng
    url: https://www.linkedin.com/in/guangming-yang-0ab9811a9/
    desc: Connect with me on LinkedIn
    share: true

theme: jekyll-theme-merlot
